kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: hotelapp
spec:
  selector:
    app: hotelapp-frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
