apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
  namespace: hotelapp
  labels:
    app:  hotelapp-frontend
spec:
  selector:
    matchLabels:
      app: hotelapp-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app:  hotelapp-frontend
    spec:
      containers:
      - name:  hotelapp-frontend
        image:  vilasdevops/hotel-frontend:latest
        ports:
        - containerPort:  5073
      restartPolicy: Always
