apiVersion: v1
kind: Secret
metadata:
  name: hotelapp-secrets
  namespace: hotelapp
type: Opaque
stringData:
  username: root
  password: root
  jwt: c2VjcmV0
  MONGO_URI: mongodb://root:root@mongodb-service:27017/hotelbooking?authSource=admin
 
