apiVersion: v1
kind: Secret
metadata:
  name: hotelapp-secrets
  namespace: hotelapp
type: Opaque
data:
  username: root
  password: root
  jwt: c2VjcmV0
  mongodb-uri:mongodb://root:root@mongodb-service:27017/hotelbooking?authSource=admin

 